name: Build fibonacci image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up buildkit
        run: |
          echo "experimental=enabled" | sudo tee -a /etc/docker/daemon.json
          sudo service docker restart
      - name: Build image
        run: |
          docker build -t fibonacci --build-arg BUILDKIT_INLINE_CACHE=1 -f Dockerfile .
      - name: Publish to GitHub Packages
        uses: docker/publish-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: Shogun-PB/fibonacci
          image_name: fibonacci
          image_tag: latest
      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCES_TOKEN }}
          repository: shogunpb/fibonacci
          build_args: |
            --build-arg BUILDKIT_INLINE_CACHE=1
          tags: |
            latest
