name: Build fibonacci image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCES_TOKEN }}
      - name: Set up Docker Buildkit
      uses: docker/setup-buildkit-action@v1
      - name: Build and push image
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,darwin/amd64 -t ghcr.io/<Shogun-PB>/fibcalc:$(date +%s) --push .
      - name: Publish to GitHub Packages
        uses: docker/publish-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: Shogun-PB/fibonacci
          image_name: fibonacci
          image_tag: latest
      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCES_TOKEN }}
          repository: shogunpb/fibonacci
          build_args: |
            --build-arg BUILDKIT_INLINE_CACHE=1
          tags: |
            latest
