name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: fibcalc

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          # ${{ secrets.USER_NAME }}/fibonacci
          ghcr.io/${{ github.repository_owner }}/fibonacci-vue
        tags: fibcalc

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.ACCES_TOKEN}}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: fibcalc
        